name: PR
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn

    - name: Set network env for main branch
      if: github.ref == 'refs/heads/main'
      run: echo "NETWORK=kepler" >> $GITHUB_ENV

    - name: Set network env for develop branch
      if: github.ref == 'refs/heads/develop'
      run: echo "NETWORK=testnet" >> $GITHUB_ENV

    - name: build
      run: yarn build

    - name: lint
      run: yarn lint

    - name: test
      run: yarn test --forceExit
      env:
        AUTH_URL: ${{ vars.AUTH_URL }}

