name: 'Prerelease'
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      force-release:
        type: boolean
        description: 'Force to publish the packages'
        default: false
        required: true

jobs:
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

  Bump-Prerelease-Publish:
    name: Bump-Prerelease-Publish
    needs: pre-ci
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && !startsWith(github.event.head_commit.message, '[release]') && github.repository == 'subquery/network-clients'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: marceloprado/has-changed-path@v1
        id: changed-network-config
        with:
          paths: packages/network-config

      - uses: marceloprado/has-changed-path@v1
        id: changed-network-support
        with:
          paths: packages/network-support

      - uses: marceloprado/has-changed-path@v1
        id: changed-eth-provider
        with:
          paths: packages/eth-provider

      - uses: marceloprado/has-changed-path@v1
        id: changed-network-clients
        with:
          paths: packages/network-clients

      - uses: marceloprado/has-changed-path@v1
        id: changed-network-query
        with:
          paths: packages/network-query

      - uses: marceloprado/has-changed-path@v1
        id: changed-react-hooks
        with:
          paths: packages/react-hooks

      - uses: marceloprado/has-changed-path@v1
        id: changed-apollo-links
        with:
          paths: packages/apollo-links

      - run: yarn

      - name: build
        run: yarn build

      - name: Bump network-config & deploy
        if: steps.changed-network-config.outputs.changed == 'true' || github.event.inputs.force-release
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/network-config
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump network-support & deploy
        if: steps.changed-network-support.outputs.changed == 'true' || github.event.inputs.force-release
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/network-support
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump eth-provider & deploy
        if: steps.changed-eth-provider.outputs.changed == 'true' || steps.changed-network-support == 'true' || github.event.inputs.force-release
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/eth-provider
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump network-query & deploy
        if: steps.changed-network-query.outputs.changed == 'true' || github.event.inputs.force-release
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/network-query
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump network-clients & deploy
        if: steps.changed-network-clients.outputs.changed == 'true' || github.event.inputs.force-release
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/network-clients
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump react-hooks & deploy
        if: steps.changed-react-hooks.outputs.changed == 'true' || steps.changed-network-query.outputs.changed == 'true' || github.event.inputs.force-release
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/react-hooks
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Bump apollo-links & deploy
        if: steps.changed-apollo-links.outputs.changed == 'true' || steps.changed-network-support == 'true' || github.event.inputs.force-release
        uses: ./.github/actions/create-prerelease
        with:
          package-path: packages/apollo-links
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: '[SKIP CI] Prerelease'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
